### ISSUE TITLE
KLJB Basis Setup

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_kljb#1]
Basis Setup 

Achtung: Der Betrieb wird von KLJB selber übernommen. Wir erstellen nur den Wagon ohne OpenShift/Mail, etc Infrastruktur

Vorgehen gemäss Anleitung: https://wiki.puzzle.ch/Hitobito/ProjektSetup

- [x] Neuen Wagon erstellen
- [x] ~Entsprechende Travis Build Jobs einrichten (.travis.yml im Wagon und auf travis integration auf github aktivieren)~
- [x] Github Action einrichten (analog zum offenen PR im PBS Wagon https://github.com/hitobito/hitobito_pbs/pull/190)
- [x] Währung auf Euro stellen
- [x] Logo
- [x] Design

# Klären mit KLJB

- [x] Verwendete Sprachen -> Nur deutsch
- [x] Logo -> Siehe Nextcloud: Nextcloud/swe/projects/KLJB_Paderborn/Hitobito/1_Dokumentation
- [x] Design -> Siehe Nextcloud: Nextcloud/swe/projects/KLJB_Paderborn/Hitobito/1_Dokumentation
- [x] Abbilden von Bundesverband, und Landesverbände -> aktuell kein Thema
- [x] Gibt es bereits eine Integrationsumgebung bei KLJB -> noch nicht vorhanden
- [x] Spezielle Anforderungen DSGVO -> nein
- [x] Support bei der Prod-Umgebung notwendig? -> noch nicht vorhanden

Hitobito Gruppen und Rechte

    • Diözesanverband 
            ▪ Fördermitglied [:passive]
            ▪ IT-Support [:admin, :impersonation, :layer_and_below_full]
        ◦ Diözesanvorstand
            ▪ Seelsorger*in [:layer_and_below_full, :contact_data]
            ▪ Vorstand [:layer_and_below_full, :contact_data]
            ▪ Beratend [:layer_read]
        ◦ Büro
            ▪ Verwaltungsleitung [:layer_and_below_full, :contact_data]
            ▪ Referent*in [:layer_and_below_full, :contact_data]
            ▪ Sekretariat [:layer_and_below_full, :contact_data]
            ▪ Mitarbeiter*in [:layer_and_below_read, :layer_full]
        ◦ AG
            ▪ Sprecher*in [:group_full, :contact_data]
            ▪ Mitglied [:group_read]
        ◦ Kontakte
            ▪ Kontakt [self.visible_from_above = false, :external]
            ▪ Teamer*in [self.visible_from_above = false, :external]
        ◦ Regionalverband
                • Fördermitglied [self.visible_from_above = false; :passive]
            ▪ Vorstand
                • Vorsitz [:layer_and_below_full, :contact_data]
                • Geist [:layer_and_below_full, :contact_data]
                • Finanzverantwortliche*r [:layer_and_below_full, :contact_data]
                • Mitglied [:layer_full, :layer_and_below_read, :contact_data]
            ▪ AG
                • S.o.
            ▪ Kontakte
                • Kontakt [self.visible_from_above = false, :external]
            ▪ Ortsgruppe
                    ◦ Fördermitglied [self.visible_from_above = false; :passive]
                    ◦ Mitglied [:member]
                • Vorstand
                    ◦ S.o.
                • AG
                    ◦ S.o.
                • Kontakte
                    ◦ Kontakt [self.visible_from_above = false, :external]
                • Leiterrunde
                    ◦ Leiter*in [:layer_and_below_read]

Aus der Doku: https://github.com/hitobito/hitobito/blob/master/doc/architecture/08_konzepte.md
`

> A Roletype can additional be of a specific kind self.kind = :external which is used in certain views to differentiate between different kinds of role. The core defines the following kinds: [:member, :passive, :external]. But this has no influence on permissions.

`

**Comment by kronn** [comment]
Der Code ist nicht auf einem PR/Feature-Branch, da er die Grundlage bildet. Review umfasst also die erste 16 Commits.

**Comment by carlobeltrame** [comment]
Approved! Was mir beim durchlesen der Commits aufgefallen ist:
https://github.com/hitobito/hitobito_kljb/blob/master/db/seeds/development/1_people.rb#L22 könnte aktueller sein
https://github.com/hitobito/hitobito_kljb#readme die Rollen sehen noch nicht so toll aus
