### ISSUE TITLE
KLJB Einfache Statistik

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_kljb#3]
Auf Layer ein neues Tab "Statistik"

## Aufschlüsseln nach Jahrgang pro Layer

Titel: Demographie

1. Spalte: Jahrgang
2. Spalte: Alter
3. Spalte: Anzahl
4. Spalte: Balken (siehe Mockup unten)

Nur Personen welche eine aktive Rolle haben, werden gezählt.

## Frage und Antworten:

* Nur aktueller Layer oder auch darunter liegende Layer
	* -> aktuell nur den Layer, Erweiterung mit aktiver Layer und darunterliegender.
* Permissions
	* -> Für Personen mit Layer_full und layer_and_below_full
* Core Feature? 
	* -> abschaltbar via Settings (Default eingeschaltet)

# Mockup

Beispiel von der PBS (https://pbs.puzzle.ch/de/groups/1/population):
![image](https://user-images.githubusercontent.com/9592347/112108952-35062700-8bb1-11eb-8f25-518619b0cf21.png)

# Tech-Spec

- [x] Domain-Klasse zum Berechnen `Groups::Demographic.new(layer).calculate`
	- [x] `calculate` gibt die Daten der kompletten Liste zurück
	- [x] Alle Gruppen des Layers sammeln und dann alle Rollen dazu holen.
	- [x] Zu den Rollen dann die Personen holen und deren Alter berechnen.
	- [x] Nach Alter gruppieren.
	- [x] die komplette Liste hat die Zeilen und allgemeine Informationen
	- [x] ein Zeile kann ein Hash, ein Struct oder ein neues Domain-object sein.
	- [x] Der Balken wird aus der Anzahl von einem formatting-helper in das richtige Markup umgewandelt wird.
	- [x] die allgemeinen Infos enthalten die maximale Anzahl der Mitglieder in einer Zeile
	- [x] die allgemeinen Infos enthalten die Gesamtzahl der Mitglieder im Layer
- [x] neues Tab in `app/helper/sheet/group.rb`
	- [x] sichtbar für Personen mit `layer_full` und `layer_and_below_full`
	- [x] Visualisierung aus dem PBS-Wagon abschauen (s. o.)
- [x] settings.yml erweitern
	- [x] `group.demographic_stats.enabled: true`
- [x] CHANGELOG-Eintrag
	- [x] "Einfache Mitgliederstatistik"

**Comment by severinraez** [comment]
Sieht momentan so aus:

![Bildschirmfoto von 2022-01-25 11-09-14](https://user-images.githubusercontent.com/849406/150956794-8e9bf812-ca34-42ce-842f-90e18c203887.png)

Fragen:

- Zu Tech-Spec
  - _die komplette Liste hat die Zeilen und allgemeine Informationen_ - passt das so?
  - _die allgemeinen Infos enthalten die maximale Anzahl der Mitglieder in einer Zeile_ - geht's hier um den maximalen Wert in der Spalte "Anzahl"? Ich könnte sonst über der Spalte "Alle" eine Spalte "Maximum" mit diesem Wert hinzufügen.
- Zum Input von Manuel
  - Momentan wird über alle Rollen ausgewertet. Was benötigen wir, damit alle Kunden profitieren?
    - a) alle Personen zählen
    - b) immer nur die Personen mit der Rolle Mitglied zählen
    - c) eine Tabelle pro Rolle
    - d) auszuwertende Rolle per Dropdown auswählen
- Ich hab' über der Tabelle einen erklärenden Satz hinzugefügt, welche Layers und Gruppen für die Statistik berücksichtigt werden. So ist z.B klar, warum in der Statistik mehr Mitglieder ersichtlich sind als im Reiter "Personen". Passt das?
