### ISSUE TITLE
Rollen von Anlässen

### ISSUE THREAD

**Issue by olibrian** [hitobito/hitobito_kljb#8]
Anpassen der Rollen auf dem Event:

Leitung: event_full, participations_full, qualify (core standard)

Teamer*in: participations_full

Helfer*in: participations_read (core standard)

Teilnehmer*in  (core standard)

**Comment by mtnstar** [comment]
heute sind folgende Rollen definiert:

![image](https://user-images.githubusercontent.com/655627/141940677-04073912-9efd-4df9-a257-e7b89fdb0776.png)
